pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        IMAGE_NAME = "tselotmillion/messaging_app"
        BRANCH_NAME = "main"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${BRANCH_NAME}",
                    url: 'https://github.com/Tselot8/alx-backend-python.git',
                    credentialsId: 'github-alx-backend'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'python -m pip3 install --upgrade pip'
                bat 'python -m pip3 install -r messaging_app\\requirements.txt'
                bat 'python -m pytest --junitxml=results.xml || exit 0'
                junit 'results.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t %IMAGE_NAME% messaging_app\\"
            }
        }

        stage('Push Docker Image') {
            steps {
                bat "echo %DOCKERHUB_CREDENTIALS_PSW% | docker login -u %DOCKERHUB_CREDENTIALS_USR% --password-stdin"
                bat "docker push %IMAGE_NAME%"
            }
        }
    }
}
