pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = credentials('github-alx-backend')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Tselot8/alx-backend-python.git', credentialsId: 'github-alx-backend'
            }
        }

        stage('Setup Python') {
            steps {
                bat 'python -m venv venv'
                bat 'venv\\Scripts\\activate && python -m pip install --upgrade pip'
                bat 'venv\\Scripts\\activate && python -m pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'venv\\Scripts\\activate && pytest messaging_app\\tests --junitxml=report.xml'
            }
        }

        stage('Archive Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
