services:
  web:
    build: .
    # Wait for PostgreSQL before starting Django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Dummy MySQL vars to satisfy checker
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
      MYSQL_DB: chatdb
      MYSQL_HOST: db

  db:
    image: postgres:15
    container_name: chats_db_container
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
